### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by di48l069** [Weshnaw/Discord-Bot#9]
Hey bud @Weshnaw 

Been browsing a bot that I can use for my own structure and came across yours.

If I may ask can I use your code in my bot named guildmonkey.
Reason why I want to do this is because I want to dedicate my bot to something specific.

**So I will be wanting to tear pieces from your application if I may do this would you like me to provide you any credits?**

Also I'm very experienced with wpf so when I am done with my alpha version I will add you if you want and if you need any help with wpf I'm willing to help.

**Comment by Weshnaw** [comment]
Go for it @di48l069! 
I would like credit, but this project is just a hobby thing that I did to practice coding (I'm fairly new) so if you see anything blindingly wrong let me know! Otherwise, just have fun and knowing someone got use out of it would make me happy.

**Comment by di48l069** [comment]
@Weshnaw Thanks, If you need any help just ask.
